name: Tygodniowy Tracker Ceny Camper

on:
  schedule:
    # Uruchamia się w każdy poniedziałek o 08:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch: # Pozwala na ręczne uruchomienie skryptu kliknięciem

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Pobranie repozytorium
      uses: actions/checkout@v3

    - name: Konfiguracja Pythona
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalacja zależności
      run: |
        pip install -r requirements.txt

    - name: Uruchomienie skryptu
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python scraper.py
